name: cyber deplyment
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: buildstep
        run: echo "building cyber project"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: teststep
        run: echo "Running cyber app test cases"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploystep
        run: echo "Depying the cyber application"
     
        
    
