name: cyber app deployemnt
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "Started build step"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test step
        run: echo "Started test step"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy step
        run: echo "Started deploy step"
